routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/admin', function () {
//     return view('admin.index');

// });


// -------------all admin controller--------------
Route::group(['middleware' => 'auth'],
    function () {
        Route::resource('/admin', 'MainAdminController');
        Route::resource('Slider', 'SliderController');
        Route::resource('SpeacialVideo', 'speacialVideoController');
        Route::resource('Studentfeedback', 'studentFeedbackAdminController');
        Route::resource('UpcomingSeminar', 'upcomingSeminarcontroller');
        Route::resource('CourseAdmin', 'courseadminController');
        Route::resource('CertificationAdmin', 'certifcationProgramadminController');
        Route::resource('OurProgramAdmin', 'ourProgramadminController');
        Route::resource('AboutOurTrainingAdmin', 'aboutourTrainingadminController');

        Route::resource('CourseModule', 'AdminCoursemoduleController');
        Route::resource('SoftwareModule', 'AdminSoftwaremoduleController');
        Route::resource('AdminMultigallery', 'AdminMultiGalleryController');
        Route::resource('AdminBlog', 'adminBlogController');
        Route::resource('AdminTutorial', 'adminTutorialController');
        Route::resource('AdminNotice', 'adminNoticeController');
        Route::resource('StudentAdminProject', 'studentProjectAdmin_Controller');
        Route::resource('FeedbackShow', 'feedback_controller');
        Route::resource('StudentApplicationBackend', 'StudentApplicationController');






    });




// --------using route and Home about Controller----
Route::resource('/','MainpageController');
Route::resource('Homepage','MainpageController');
Route::resource('HomeAbout','AboutHomeController');
Route::get('HomeFounderCompany.aboutCompanyFounder','AboutHomeController@aboutCompanyFounder')->name('HomeFounderCompany.aboutCompanyFounder');

Route::resource('UpdateBatch','updateBatchHomeController');
Route::resource('ContactHome','ContactHomeController');
Route::resource('NoticeHome','NoticeHomeController');
Route::resource('TrainingHome','TrainingHomeController');
Route::resource('Professional','ProfessionalCourseConroller');
Route::resource('DiplomaCourse','DiplomaCourseConroller');
Route::resource('FreeSeminner','FreeSeminarController');
Route::resource('ITsecurity','ITsecurityCourseConroller');

Route::resource('Blog','BlogController');
Route::resource('Tutorial','TutorialController');
Route::resource('StudentGallery','StudentGalleryController');
Route::resource('TeacherGallery','TeacherGalleryController');
Route::resource('OfficeGallery','OfficeGalleryController');
Route::resource('DoofazitEvent','DoofazitEventController');
Route::resource('LabProgram','LapProgramController');
Route::resource('NoticeView','NoticeHomeController');
Route::resource('StudentProject','studentProject_Controller');
Route::resource('FeedbackStudent','feedback_controller');


Auth::routes();

Route::get('/home', 'HomeController@index');



//<------------------------MenuSetup------------------------->

Route::resource('addCategory','categoryController');
Route::resource('addSubCategory','subCategoryController');


//<-------------------------Header News-------------------------------------->

Route::resource('addnewsheader','headerNewsController');


//<.......................Student Application route.................................>

app/CoursemoduleInfo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CoursemoduleInfo extends Model
{
    protected $table = 'course_module';
}

app/FeedbackModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FeedbackModel extends Model
{
     protected $table = 'feedback_student';
}

app/SoftwaremoduleInfo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SoftwaremoduleInfo extends Model
{
    protected $table = 'software_module';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/blogModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class blogModel extends Model
{
   protected $table = 'blog';
}

app/category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class category extends Model
{
    protected $table = 'categories';

    public function subCategories(){
        return $this->hasMany('App\category');
    }

}

app/certificationmodel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class certificationmodel extends Model
{
    protected $table = 'certificationprogram';
}

app/coursemodel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class coursemodel extends Model
{
  protected $table = 'course';
}

app/diploma_studentModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class diploma_studentModel extends Model
{
   protected $table = 'diploam_student';
   protected $fillable=['status'];
}

app/freeSeminarModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class freeSeminarModel extends Model
{
   protected $table = 'free_course_student';
   protected $fillable=['status'];
}

app/headerNews.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class headerNews extends Model
{
    protected $table = 'header_news';


}

app/itsecurityModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class itsecurityModel extends Model
{
    protected $table = 'itsecurity_course';
    protected $fillable=['status'];
}

app/multiGallerymodel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class multiGallerymodel extends Model
{
    protected $table = 'multi_gallery';
}

app/noticeModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class noticeModel extends Model
{
    protected $table = 'notice';
}

app/ourProgrammodel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ourProgrammodel extends Model
{
    protected $table = 'ourprogram';
}

app/slideModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class slideModel extends Model
{
    protected $table = 'slider';
}

app/specialvideoModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class specialvideoModel extends Model
{
   protected $table = 'specialvideo';
}

app/studentfeedback.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class studentfeedback extends Model
{
    //
}

app/subcategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class subcategory extends Model
{
    protected $table = 'subcategories';



    public function Category(){
        return $this->belongsTo('App\category');
    }
}

app/tutorialModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class tutorialModel extends Model
{
   protected $table = 'tutorial';
}

resources/views/Menu/category.blade.php
@extends('admin.layouts.header')
@section('admin-container')
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="{{Route('admin.index')}}">Home</a>
                    </li>

                </ul><!-- /.breadcrumb -->

                <div class="nav-search" id="nav-search">
                    <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input"
                               autocomplete="off"/>
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                    </form>
                </div>
            </div>


            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                <div class="widget-body">
                    <div class="widget-main">
                        <div id="fuelux-wizard-container">
                            <h3 class="text-center">Add Category Information </h3>

                            <hr/>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                                    <div class="step-content pos-rel">
                                        <div class="step-pane active" data-step="1">
                                            <div class="col-md-8 col-md-offset-2">
                                                @if (count($errors) > 0)
                                                    <div class="alert alert-danger">
                                                        <ul>
                                                            @foreach ($errors->all() as $error)
                                                                <li>{{ $error }}</li>
                                                            @endforeach
                                                        </ul>
                                                    </div>
                                                @endif
                                            </div>

                                            <form action="{{ route('addCategory.store') }}" method="post"
                                                  enctype="multipart/form-data" class="form-horizontal"
                                                  id="sample-form">

                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
                                                    <div class="form-group">
                                                        <label for="title">Title</label>
                                                        {{ csrf_field()}}

                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                <span class="block input-icon input-icon-right">
                                    <input type="text" name="title" placeholder="Title" id="title" class="width-100"/>
                                    <i class="ace-icon fa fa-leaf"></i>
                                </span>
                                                        </div>
                                                    </div>


                                                    <div class="form-group">
                                                        <label for="link">Url link</label>
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                <span class="block input-icon input-icon-right">
                                    <input type="text" name="url" placeholder="Url" id="link"
                                           class="width-100"/>
                                    <i class="ace-icon fa fa-leaf"></i>

                                </span>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="title">Position</label>
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                                <span class="block input-icon input-icon-right">
                                                                    <input type="text" name="position" placeholder="Position" id="icon"
                                                                           class="width-100"/>
                                                                    <i class="ace-icon fa fa-leaf"></i>
                                                                </span>
                                                        </div>
                                                    </div>


                                                    <div class="form-group">
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                            <span class="block input-icon input-icon-right">
                                                                <input type="checkbox" id="publish" class="filled-in" name="status" value="1">
                                                                 <label for="publish">Publish</label>

                                                            </span>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                            <span class="block input-icon input-icon-right">
                                                                <input type="checkbox" id="publish" class="filled-in" name="sub_status" value="1">
                                                                 <label for="publish">Sub_Title_status</label>

                                                            </span>
                                                        </div>
                                                    </div>



{{--                                                    <div class="form-group">--}}
{{--                                                        <label for="photo">Photo</label>--}}
{{--                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">--}}
{{--                                <span class="block input-icon input-icon-right">--}}
{{--                                    <input type="file" name="image" id="photo"/>--}}

{{--                                </span>--}}
{{--                                                        </div>--}}
{{--                                                    </div>--}}


                                                    <div class="form-group">
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">

                                                            <input type="submit" value="Submit"
                                                                   name="Subject_name_submit" class="btn btn-primary"/>


                                                        </div>
                                                    </div>
                                                </div>


                                            </form>

                                        </div>
                                    </div>

                                </div>
                            </div>


                        </div>
                    </div>

                    <div class="col-md-6 col-md-offset-3">
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif
                    </div>

                </div>


                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="head-title"><h3>View information</h3></div>
                        <table class="table table-bordered table-responsive">
                            <tr>
                                <th>Sl</th>
                                <th>Title</th>
                                <th>Url Link</th>
                                <th>Position</th>
                                <th>Action</th>
                            </tr>

                            @foreach($data AS $value)
                                <tr>
                                    <td>{{$value->id}}</td>
                                    <td>{{$value->title}}</td>
                                    <td>{{$value->url}}</td>
                                    <td>{{$value->position}}</td>



                                    <td>
                                            <a class="green" href="{{ route('addCategory.edit',$value->id) }}">
                                                <span class="glyphicon glyphicon-edit fa-2x"></span>
                                            </a>

                                            <form action="{{ url('addCategory/'.$value->id) }}" method="post">
                                                {{ csrf_field()}}
                                                {{ method_field('DELETE')}}
                                                <button class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></button>
                                            </form>



                                    </td>
                                </tr>
                            @endforeach

                        </table>
                    </div>
{{--                    {{$special->links()}}--}}
                </div>


            </div>


        </div>
    </div>
@endsection

resources/views/Menu/sub_category.blade.php
@extends('admin.layouts.header')
@section('admin-container')
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="{{Route('admin.index')}}">Home</a>
                    </li>

                </ul><!-- /.breadcrumb -->

                <div class="nav-search" id="nav-search">
                    <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input"
                               autocomplete="off"/>
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                    </form>
                </div>
            </div>


            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                <div class="widget-body">
                    <div class="widget-main">
                        <div id="fuelux-wizard-container">
                            <h3 class="text-center">Add SubCategory Information </h3>

                            <hr/>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                                    <div class="step-content pos-rel">
                                        <div class="step-pane active" data-step="1">
                                            <div class="col-md-8 col-md-offset-2">
                                                @if (count($errors) > 0)
                                                    <div class="alert alert-danger">
                                                        <ul>
                                                            @foreach ($errors->all() as $error)
                                                                <li>{{ $error }}</li>
                                                            @endforeach
                                                        </ul>
                                                    </div>
                                                @endif
                                            </div>




                                            <form action="{{ route('addSubCategory.store') }}" method="post"
                                                  enctype="multipart/form-data" class="form-horizontal"
                                                  id="sample-form">
                                                {{ csrf_field()}}
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">



                                                    <div class="form-group">
                                                        <label for="title">Select Category</label>
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                            <select name="title" id="title" class="form-control show-tick" data-live-search="true" >
                                                                @foreach($value as $category)
                                                                    <option value="{{ $category->id }}">{{ $category->title }}</option>
                                                                @endforeach
                                                            </select>
                                                        </div>
                                                    </div>



                                                    <div class="form-group">
                                                        <label for="title">Sub Category Title</label>
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                            <span class="block input-icon input-icon-right">
                                                                <input type="text" name="sub_title" placeholder="Title" id="title" class="width-100"/>
                                                                <i class="ace-icon fa fa-leaf"></i>
                                                            </span>
                                                        </div>
                                                    </div>



                                                    <div class="form-group">
                                                        <label for="title">URL</label>

                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                            <span class="block input-icon input-icon-right">
                                                                <input type="text" name="sub_link" placeholder="URL" id="url" class="width-100"/>
                                                                <i class="ace-icon fa fa-leaf"></i>
                                                            </span>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="title">Position</label>
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                                <span class="block input-icon input-icon-right">
                                                                    <input type="number" name="position" placeholder="Position" id="icon"
                                                                           class="width-100"/>
                                                                    <i class="ace-icon fa fa-leaf"></i>
                                                                </span>
                                                        </div>
                                                    </div>


                                                    <div class="form-group">
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                            <span class="block input-icon input-icon-right">
                                                                <input type="checkbox" id="publish" class="filled-in" name="publish" value="1">
                                                                 <label for="publish">Publish</label>

                                                            </span>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">
                                                            <span class="block input-icon input-icon-right">
                                                                <input type="checkbox" id="publish" class="filled-in" name="status" value="1">
                                                                 <label for="publish">Sub_Title_status</label>

                                                            </span>
                                                        </div>
                                                    </div>




                                                    <div class="form-group">
                                                        <div class="col-xs-12 col-sm-12 col-md-12 padding">

                                                            <input type="submit" value="Submit"
                                                                    class="btn btn-primary"/>

                                                        </div>
                                                    </div>
                                                </div>
                                            </form>

                                        </div>
                                    </div>

                                </div>
                            </div>


                        </div>
                    </div>

                    <div class="col-md-6 col-md-offset-3">
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif
                    </div>

                </div>




                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <h3 class="text-center">Add SubCategory Information </h3>

                        <hr/>



                        <table class="table table-bordered table-responsive">
                            <tr>
                                <th>Sl</th>
                                <th>Category</th>
                                <th>Sub Category Title</th>
                                <th>URL</th>
                                <th>Position</th>
                                <th>Action</th>
                            </tr>




                            @foreach($data AS $key=>$value)
                                <tr>
                                    <td>{{$key+1}}</td>
                                    @if($value->category_id)
                                        <td>{{$value->category->title}}</td>
                                        @else
                                        <td>
                                            ----
                                        </td>
                                    @endif
                                    <td>{{$value->sub_title}}</td>
                                    <td>{{$value->sub_link}}</td>

                                    <td>{{$value->position}}</td>
                                    <td>
                                        <a class="green" href="{{ route('addSubCategory.edit',$value->id) }}">
                                            <span class="glyphicon glyphicon-edit fa-2x"></span>
                                        </a>

                                        <form action="{{ route('addSubCategory.destroy',$value->id) }}" method="post">
                                            {{ csrf_field()}}
                                            {{ method_field('DELETE')}}
                                            <button class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></button>
                                        </form>



                                    </td>

                                </tr>
                            @endforeach

                        </table>
                    </div>
{{--                    {{$data->links()}}--}}
                </div>


            </div>


        </div>
    </div>

@endsection

@push('js')


@endpush

resources/views/noticeDetails.blade.php
@extends('layouts.header')
@section('main-container')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">

                <div class="col-md-12 col-sm-12 col-xs-12 padding">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 Notice-header">
                            <h3> PREVIOUS Notice Information </h3>
                            <b>DoofazIT </b>
                        </div>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12 StudentGallery-area padding">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding" style="margin-top: 10px;">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 title-header padding">
                                <h3 class="text-center"> Notice Information Details </h3>
                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12  notice-board">
                                <h3>{{$info->title}}</h3>
                                <p>
                                    {{$info->description}}
                                </p>

                            </div>


                        </div>
                    </div>

                    <!-- --------------End--model-thumbnai -->


                </div>
            </div>
        </div>
        <script type="text/javascript">

        </script>

    </div>
@endsection